<a href="https://colab.research.google.com/github/sasya05/CP/blob/main/Lab_1_2_3_pds.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
def factorial(n):
    # Base Case
    if n == 0 or n == 1:
        return 1

    # Recursive Case
    else:
        return n * factorial(n - 1)


num = int(input("Enter a number: "))

# Check for negative numbers
if num < 0:
    print("Factorial is not defined for negative numbers.")
else:
    result = factorial(num)
    print(f"Factorial of {num} = {result}")

Enter a number: 10
Factorial of 10 = 3628800


In [6]:
def sum_of_digits(n):
    # Base Case
    if n == 0:
        return 0

    # Recursive Case
    return (n % 10) + sum_of_digits(n // 10)


# Accept user input
number = int(input("Enter a positive integer: "))

# Handle negative numbers
if number < 0:
    print("Please enter a positive integer.")
else:
    result = sum_of_digits(number)
    print("Sum of digits =", result)

Enter a positive integer: 4
Sum of digits = 4


In [7]:
# Python Program to Reverse a String Using Recursion

def reverse_string(text):
    # Base Case
    if len(text) == 0:
        return text

    # Recursive Case
    return reverse_string(text[1:]) + text[0]


# Accept user input
string = input("Enter a string: ")

# Display the reversed string
print("Reversed String =", reverse_string(string))

Enter a string: saaya
Reversed String = ayaas


In [8]:
def count_digits(n):
    # Base Case
    if n < 10:
        return 1

    # Recursive Case
    return 1 + count_digits(n // 10)


# Accept user input
number = int(input("Enter an integer: "))

# Handle negative numbers
number = abs(number)

# Display the result
print("Number of Digits =", count_digits(number))

Enter an integer: 45
Number of Digits = 2


In [10]:
import numpy as np

marks = np.array([85, 90, 78, 88, 92])

print(marks)

[85 90 78 88 92]


In [11]:
import numpy as np
student_marks = np.array([ [85, 90, 78], [88, 76, 91], [92, 84, 80] ])
print(student_marks)

[[85 90 78]
 [88 76 91]
 [92 84 80]]


In [12]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

# Display the array
print("Array :", arr)

# Basic operations
print("Maximum Value :", arr.max())
print("Minimum Value :", arr.min())
print("Sum :", arr.sum())
print("Average :", arr.mean())
print("Number of Elements :", arr.size)

Array : [10 20 30 40 50]
Maximum Value : 50
Minimum Value : 10
Sum : 150
Average : 30.0
Number of Elements : 5


In [13]:
import numpy as np

# Create an array
arr = np.array([10, 20, 30, 40, 50])

# Indexing
print("First Element :", arr[0])
print("Last Element :", arr[-1])

# Slicing
print("Elements from Index 1 to 3 :", arr[1:4])

# Arithmetic operations
print("Array + 10 :", arr + 10)
print("Array × 2 :", arr * 2)

# Reshape
new_arr = arr.reshape(5, 1)

print("Reshaped Array:")
print(new_arr)

First Element : 10
Last Element : 50
Elements from Index 1 to 3 : [20 30 40]
Array + 10 : [20 30 40 50 60]
Array × 2 : [ 20  40  60  80 100]
Reshaped Array:
[[10]
 [20]
 [30]
 [40]
 [50]]


In [14]:
import pandas as pd

# Create a DataFrame
data = {
    "Roll No": [101, 102, 103, 104],
    "Name": ["Ravi", "Priya", "Arun", "Meena"],
    "Marks": [85, 92, 78, 88]
}

df = pd.DataFrame(data)

# Display the DataFrame
print("DataFrame")
print(df)

# Display first two rows
print("\nFirst Two Rows")
print(df.head(2))

# Display last two rows
print("\nLast Two Rows")
print(df.tail(2))

# Display column names
print("\nColumn Names")
print(df.columns)

# Display DataFrame shape
print("\nShape")
print(df.shape)

# Display summary information
print("\nInformation")
print(df.info())

# Display statistical summary
print("\nStatistical Summary")
print(df.describe())

DataFrame
   Roll No   Name  Marks
0      101   Ravi     85
1      102  Priya     92
2      103   Arun     78
3      104  Meena     88

First Two Rows
   Roll No   Name  Marks
0      101   Ravi     85
1      102  Priya     92

Last Two Rows
   Roll No   Name  Marks
2      103   Arun     78
3      104  Meena     88

Column Names
Index(['Roll No', 'Name', 'Marks'], dtype='object')

Shape
(4, 3)

Information
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   Roll No  4 non-null      int64 
 1   Name     4 non-null      object
 2   Marks    4 non-null      int64 
dtypes: int64(2), object(1)
memory usage: 228.0+ bytes
None

Statistical Summary
          Roll No      Marks
count    4.000000   4.000000
mean   102.500000  85.750000
std      1.290994   5.909033
min    101.000000  78.000000
25%    101.750000  83.250000
50%    102.500000  86.500000
75%    103.250000  89.

In [15]:
import numpy as np

A = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

B = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print("\nArray A:")
print(A)

print("\nArray B:")
print(B)

# Addition
print("\nAddition (A + B):")
print(A + B)

# Subtraction
print("\nSubtraction (A - B):")
print(A - B)

# Element-wise Multiplication
print("\nElement-wise Multiplication (A * B):")
print(A * B)


Array A:
[[10 20 30]
 [40 50 60]]

Array B:
[[1 2 3]
 [4 5 6]]

Addition (A + B):
[[11 22 33]
 [44 55 66]]

Subtraction (A - B):
[[ 9 18 27]
 [36 45 54]]

Element-wise Multiplication (A * B):
[[ 10  40  90]
 [160 250 360]]


In [16]:
import numpy as np

A = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

B = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print("\nArray A:")
print(A)

print("\nArray B:")
print(B)

# Addition
print("\nAddition (A + B):")
print(A + B)

# Subtraction
print("\nSubtraction (A - B):")
print(A - B)

# Element-wise Multiplication
print("\nElement-wise Multiplication (A * B):")
print(A * B)

# Element-wise Division
print("\nElement-wise Division (A / B):")
print(A / B)

# Matrix C
C = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])

print("\nMatrix C:")
print(C)

# Matrix Multiplication
print("\nMatrix Multiplication (A @ C):")
print(A @ C)


Array A:
[[10 20 30]
 [40 50 60]]

Array B:
[[1 2 3]
 [4 5 6]]

Addition (A + B):
[[11 22 33]
 [44 55 66]]

Subtraction (A - B):
[[ 9 18 27]
 [36 45 54]]

Element-wise Multiplication (A * B):
[[ 10  40  90]
 [160 250 360]]

Element-wise Division (A / B):
[[10. 10. 10.]
 [10. 10. 10.]]

Matrix C:
[[1 2]
 [3 4]
 [5 6]]

Matrix Multiplication (A @ C):
[[220 280]
 [490 640]]


In [17]:
import numpy as np

A = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

print(A)

# Shape and Dimensions
print("Shape:", A.shape)
print("Dimensions:", A.ndim)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Shape: (2, 2, 2)
Dimensions: 3
